name: 'context'

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: ./provision

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Post the plan on the PR'
      uses: actions/github-script@v4.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log(context)
