name: 'merged'

on:
  pull_request:
    types: [closed]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: 'Post the plan on the PR'
      if: github.event.pull_request.merged == true
      uses: actions/github-script@v4.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log(context)
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "✅"
          })
